# Generated by Django 2.2.20 on 2021-04-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionadmin',
            name='question_ptr',
        ),
        migrations.RemoveField(
            model_name='useradmin',
            name='question_ptr',
        ),
        migrations.AddField(
            model_name='answer',
            name='marked_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='AnswerAdmin',
        ),
        migrations.DeleteModel(
            name='QuestionAdmin',
        ),
        migrations.DeleteModel(
            name='UserAdmin',
        ),
    ]
