# Generated by Django 2.2.20 on 2021-05-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answers_num',
            field=models.IntegerField(default=0),
        ),
    ]
