# Generated by Django 2.2.20 on 2021-04-20 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tag',
            table='tags',
        ),
    ]
