# Generated by Django 2.2.20 on 2021-04-20 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='text',
        ),
    ]
