# Generated by Django 2.2.20 on 2021-05-30 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_question_answers_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answers_num',
            new_name='_answers_num',
        ),
    ]
