# Generated by Django 2.2.20 on 2021-05-30 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210530_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionRatingMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(choices=[(1, 'like'), (-1, 'dislike'), (0, 'none')], default=0)),
                ('fk_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Profile')),
                ('fk_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Question')),
            ],
            options={
                'verbose_name': 'Q-VoteMark',
                'verbose_name_plural': 'Q-VoteMarks',
            },
        ),
        migrations.CreateModel(
            name='AnswerRatingMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(choices=[(1, 'like'), (-1, 'dislike'), (0, 'none')], default=0)),
                ('fk_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Answer')),
                ('fk_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Profile')),
            ],
            options={
                'verbose_name': 'A-VoteMark',
                'verbose_name_plural': 'A-VoteMarks',
            },
        ),
    ]
