# Generated by Django 2.2.20 on 2021-05-30 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_answerratingmark_questionratingmark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='rating',
            new_name='_rating',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='rating',
            new_name='_rating',
        ),
    ]
