# Generated by Django 2.2.20 on 2021-05-29 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210530_0205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='fk_user',
            new_name='fk_profile',
        ),
    ]
