# Generated by Django 2.2.20 on 2021-05-29 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210530_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatarlink',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
