# Generated by Django 2.2.20 on 2021-05-30 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210530_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='fk_user',
        ),
        migrations.AddField(
            model_name='answer',
            name='fk_profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Profile'),
            preserve_default=False,
        ),
    ]
