# Generated by Django 2.2.20 on 2021-05-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210530_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='fk_question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='answers_num',
        ),
        migrations.AddField(
            model_name='question',
            name='fk_answers',
            field=models.ManyToManyField(to='app.Answer'),
        ),
    ]
