# Generated by Django 2.2.20 on 2021-05-30 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210530_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='fk_answers',
        ),
        migrations.AddField(
            model_name='answer',
            name='fk_question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='answers_num',
            field=models.IntegerField(default=0),
        ),
    ]
