# Generated by Django 2.2.20 on 2021-05-30 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210530_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='fk_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Question'),
        ),
    ]
